### ISSUE TITLE
Prevent a job that fails to JSON decode from being released to the queue with zero second delay

### ISSUE THREAD

**Issue by tomponline** [tomponline/beanstalkworker#15]
@NevilleC reports
"I tested metrics jobs but with a wrong JSON and I triggered this error in your beanstalk lib: "job.LogError("Error decoding JSON for job: ", err, ", '", string(*job.body), "', releasing...")"  The problem is the "lmp.SetReturnDelay(returnDelaySec)" has been not set at this point... It will be set after the call to "Subscribe"... so the job is coming back so quickly in the queue that it is hard to delete it...  Would it be possible to fix a default delay at this moment in the code?"

**Comment by tomponline** [comment]
The offending line is: https://github.com/tomponline/beanstalkworker/blob/master/beanstalkworker/worker.go#L45

**Comment by tomponline** [comment]
I propose setting a default delay to 60s if the received job has a delay of 0s here https://github.com/tomponline/beanstalkworker/blob/master/beanstalkworker/worker.go#L160

This can still be overridden back to 0s inside the specific handler if it correctly decodes, by executing ```SetReturnDelay(0)```

**Comment by robnorman** [comment]
Sounds fair. Being able to explicitly set a zero delay is enough for any use case I can think of.
