### ISSUE TITLE
Subscriber shouldn't release the job when there is an error to decode the JSON

### ISSUE THREAD

**Issue by NevilleC** [tomponline/beanstalkworker#26]
We were working on a new worker, and when I tested it manually, I put a wrong JSON on the queue.
I notice that the end result is a log Error (this is good) but the job was released as well. 

```
Nov 27 11:59:18 jobs01 billingjobs[30481]: Tube: callbilling, Job: 4957740: Error: Error decoding JSON for job: json: cannot unmarshal number into Go value of type string, ...(job data that I hide)..., releasing...
```
I don't understand the purpose: the job is malformed, so when it will be re-tried, it will hit the same problem. If this scenario occurs, it's a sign that the process who built the job can be broken.

The best we can do, it's to log the error and delete it. Then, we should have enough info to re-queue it later, to ensure we don't lose any data. But releasing it will simply repeat the error.

https://github.com/tomponline/beanstalkworker/blob/f880af6af406bae85607cffb56c63e34cc3b0ab9/beanstalkworker/worker.go#L61
```go
		if err := json.Unmarshal(*job.body, dataPtr.Interface()); err != nil {
			job.LogError("Error decoding JSON for job: ", err, ", '", string(*job.body), "', releasing...")
			job.Release()
			return
		}
```

**Comment by NevilleC** [comment]
The fix could be as simple as 

```diff
		if err := json.Unmarshal(*job.body, dataPtr.Interface()); err != nil {
			job.LogError("Error decoding JSON for job: ", err, ", '", string(*job.body), "', releasing...")
-			job.Release()
+                       job.Delete()
			return
		}
```

**Comment by NevilleC** [comment]
@tomponline if you agree, I am happy to write the fix for this one. Let me know as it is your package. I would like to have a confirmation before opening a PR.

**Comment by tomponline** [comment]
Hi @NevilleC 

There is a reason that the JSON Unmarshal failure returns the job to the queue. This is because I wanted the package to be safe by default, i.e it wouldn't throw jobs away, even if they were malformed.

However, I understand the issue you are explaining here, which is that if a job is malformed, then it will entry an infinite loop, being repeatedly returned to the queue until its manually removed from the tube.

Perhaps instead we could provide a way for decode errors to be handled by another handler function, where the developer can choose to delete or bury (or something else) on a per-app basis.

This way the default would still remain safe by default.

**Comment by gha** [comment]
@tomponline Is there any need to JSON decode it in the first place? Can you not just let the subscriber decide what to do with the job data?

**Comment by tomponline** [comment]
@gha the json decoding (or any transport encoding method - see https://github.com/tomponline/beanstalkworker/issues/7) is fundamental to this package, as it was my intention to use a NATS style reflection to decode a message/job directly into the function that is subscribing to that job type.

The intention of this package is to remove some of the repetitive stuff you have to do to build jobs.

**Comment by tomponline** [comment]
@gha @NevilleC We could add a worker instance level handler, e.g.

```go
bsWorker.SetUnmarshalErrorHandler(func(jobMgr beanstalkworker.JobManager, rawJobData byte[]))
```

**Comment by tomponline** [comment]
Or perhaps a simpler approach of setting unmarshal failure action of delete, release or bury.

E.g.
`
bsWorker.SetUnmarshalErrorAction(bsWorker.ActionDelete)`

**Comment by NevilleC** [comment]
@tomponline @gha I like the `bsWorker.SetUnmarshalErrorAction(bsWorker.ActionDelete)` idea.

So to be sure we are on the same page for the usage, it would be something like that in the worker process:
```go
        bsWorker.SetUnmarshalErrorAction(bsWorker.ActionDelete)
	bsWorker.Subscribe("example_queue", func(jobMgr beanstalkworker.JobManager, jobData *invoiceSaveData) {
		proc := &invoiceSaveJob{JobManager: jobMgr, configDb: configDb}
		proc.run(jobData)
	})
```

Then in the bs package, we should modify the line 63
https://github.com/tomponline/beanstalkworker/blob/f880af6af406bae85607cffb56c63e34cc3b0ab9/beanstalkworker/worker.go#L61-L65
to take into account which action the user has set.

If yes, happy to work on that on my free time.
