### ISSUE TITLE
Improve layout of the package

### ISSUE THREAD

**Issue by NevilleC** [tomponline/beanstalkworker#30]
When we import the beanstalkworker package, we are doing a double `beanstalkworker` in the import:
`import "github.com/tomponline/beanstalkworker/beanstalkworker"`

It's a little bit repetitive. Could we refactor it to ensure we just need to do write `"github.com/tomponline/beanstalkworker"`? What was the reason for this initial design?

Besides, we are building a code example, via the `beanstalkworker_demo`, which is great... but it doesn't appear in the `godoc`. It's a little bit a shame as `godoc` provides a great support to familiarise yourself with a new package.

https://godoc.org/github.com/tomponline/beanstalkworker/beanstalkworker

We could follow this example to make it available:
https://godoc.org/golang.org/x/oauth2/google
https://github.com/golang/oauth2/blob/master/google/example_test.go#L30
https://github.com/golang/oauth2/blob/master/google/example_test.go#L93

**Comment by tomponline** [comment]
Hi @NevilleC the reason I did this was to separate the examples from the actual package.

You're right I could've done a better job at this.

I've seen some repos that use the `examples` sub-folder to house the example programs. I want to make sure these programs are not build into a program called `examples` though first if a `go install` is run against the parent directory.

**Comment by tomponline** [comment]
@NevilleC using the example unit test style you've suggested is another interesting approach, I'm happy to go with that too.

**Comment by tomponline** [comment]
@NevilleC see https://github.com/tomponline/beanstalkworker/pull/31

**Comment by tomponline** [comment]
Fixed.
